### ISSUE TITLE
Add bPaideia

### ISSUE THREAD

**Issue by Luivatra** [zargarzadehm/ergoPaymentAuto#14]
bPaideia is to be used in the public beta of Paideia

name = "bPaideia"
erg = "1000000" // How much erg should be in each box?
// What token (id) and how much of it should be in each box?
0040ae650c4ed77bcd20391493abe84c1a9bb58ee88e87f15670c801e2fc5983= "100000000"

I assume this is raw tokens, not taking decimals into account?

**Comment by zargarzadehm** [comment]
We added this token to the faucet!
